package com.BillSyncOrg.BillSync.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a user entity stored in the MongoDB database.
 * <p>
 * This class is annotated with {@code @Document} to indicate it's a MongoDB collection.
 * It contains core attributes required for a registered user, including email,
 * phone number, and an encrypted password.
 * </p>
 *
 * <p>
 * The password field is stored as a BCrypt-hashed string.
 * The MongoDB collection for this entity is named "users".
 * </p>
 */
@Document(collection = "users")
public class User {

  /**
   * Unique identifier for the user, auto-generated by MongoDB.
   */
  @Id
  private String id;

  /**
   * The user's email address. Should be unique across the database.
   */
  private String email;

  /**
   * The user's 10-digit phone number. Should be unique across the database.
   */
  private String phoneNumber;

  /**
   * The user's encrypted password. Stored as a hashed string using BCrypt.
   */
  private String password;

  // Getters and Setters
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }
}
